config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("", lambda x: redirect("/home/")),
    path('admin/', admin.site.urls),
    path('mypage/', include('mypage.urls')),
    path('survey/', include('survey.urls')),
    path('travelbox/', include('travelbox.urls')),
    # path('accounts/naver/login/', lambda request:redirect("/")),
    path('accounts/', include('allauth.urls')),
    path('accounts/social/login/cancelled/', lambda request: redirect("mypage/login/")),
    path('accounts/social/login/error/', lambda request: redirect("mypage/login/")),
    path('home/', include("home.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

survey/urls.py
from unicodedata import name
from django.urls import path
from survey import views

app_name = 'survey'

urlpatterns = [
    path('survey-start/', views.question0, name='survey_q0'),
    path('survey-q1/', views.question1, name='survey_q1'),
    path('survey-q2/', views.question2, name='survey_q2'),
    path('survey-q3/', views.question3, name='survey_q3'),
    path('survey-q4/', views.question4, name='survey_q4'),
    path('survey-q5/', views.question5, name='survey_q5'),
    path('survey-q6/', views.question6, name='survey_q6'),
    path('survey-q7/', views.question7, name='survey_q7'),
    path('survey-q8/', views.question8, name='survey_q8'),
    path('survey-q9/', views.question9, name='survey_q9'),
    path('survey-q10/', views.question10, name='survey_q10'),
    path('survey-end/', views.survey_end, name='survey_end'),
]

survey/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class SurveyQuestion(models.Model):
    survey_uid = models.CharField(max_length=64)
    question0 = models.CharField(max_length=32, null=True, blank=True)
    question1 = models.CharField(max_length=32, null=True, blank=True)
    question2 = models.CharField(max_length=32, null=True, blank=True)
    question3 = models.CharField(max_length=32, null=True, blank=True)
    question4 = models.CharField(max_length=32, null=True, blank=True)
    question5 = models.CharField(max_length=32, null=True, blank=True)
    question6 = models.CharField(max_length=32, null=True, blank=True)
    question7 = models.CharField(max_length=32, null=True, blank=True)
    question8 = models.CharField(max_length=32, null=True, blank=True)
    question9 = models.CharField(max_length=32, null=True, blank=True)
    question10 = models.CharField(max_length=32, null=True, blank=True)

survey/views.py
from django.db.utils import OperationalError
from django.shortcuts import redirect, render
from survey.models import SurveyQuestion

import uuid

# Create your views here.

def question0(request):
    if request.method == "POST":
        activity_answer = SurveyQuestion()
        activity_answer.survey_uid = request.COOKIES.get("supme-survey-id")
        activity_answer.question0 = request.POST.get('start')
        activity_answer.save()
        return redirect("survey:survey_q1")
    response = render(request, 'survey/survey_q0.html')
    response.set_cookie("supme-survey-id", str(uuid.uuid4()))
    return response

# def question1(request):
#     if request.method == "POST":
#         activity_answer = SurveyQuestion()
#         activity_answer.survey_uid = request.COOKIES.get("supme-survey-id")
#         activity_answer.question1 = request.POST.get('where')
#         activity_answer.save()
#         return redirect("survey:survey_q2")
#     response = render(request, 'survey/survey_q1.html')
#     response.set_cookie("supme-survey-id", str(uuid.uuid4()))
#     return response

def question1(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question1 = request.POST.get('where')
        activity_answer.save()
        return redirect("survey:survey_q2")
    return render(request, 'survey/survey_q1.html')

def question2(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question2 = request.POST.get('gender')
        activity_answer.save()
        return redirect("survey:survey_q3")
    return render(request, 'survey/survey_q2.html')


def question3(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question3 = request.POST.get('age')
        activity_answer.save()
        return redirect("survey:survey_q4")
    return render(request, 'survey/survey_q3.html')

def question4(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question4 = request.POST.get('disposition')
        activity_answer.save()
        return redirect("survey:survey_q5")
    return render(request, 'survey/survey_q4.html')

def question5(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question5 = request.POST.get('site')
        activity_answer.save()
        return redirect("survey:survey_q6")
    return render(request, 'survey/survey_q5.html')

def question6(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question6 = request.POST.get('house')
        activity_answer.save()
        return redirect("survey:survey_q7")
    return render(request, 'survey/survey_q6.html')

def question7(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question7 = request.POST.get('weapon')
        activity_answer.save()
        return redirect("survey:survey_q8")
    return render(request, 'survey/survey_q7.html')

def question8(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question8 = request.POST.get('food')
        activity_answer.save()
        return redirect("survey:survey_q9")
    return render(request, 'survey/survey_q8.html')

def question9(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question9 = request.POST.get('seasoning')
        activity_answer.save()
        return redirect("survey:survey_q10")
    return render(request, 'survey/survey_q9.html')

def question10(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question10 = request.POST.get('stay')
        activity_answer.save()
        return redirect("survey:survey_end")
    return render(request, 'survey/survey_q10.html')

def survey_end(request):
    survey_uid = request.COOKIES.get("supme-survey-id")
    if not survey_uid:
        return redirect("mypage:home")
    if request.method == "POST":
        try:
            activity_answer = SurveyQuestion.objects.get(survey_uid=survey_uid)
        except OperationalError:
            return redirect("mypage:home")
        activity_answer.question11 = request.POST.get('send')
        activity_answer.save()
        return redirect("mypage:login")
    return render(request, 'survey/survey_q11.html')

survey/templates/survey/survey_q0.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>

<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
    <div class="wrapper">
      <div class="profile-card js-profile-card">
        <div class="profile-card__img">
          <img src="/static/survey/assets/survey0.jpg" alt="profile card">
        </div>
    
        <div class="profile-card__cnt js-profile-cnt">
          <div class="profile-card__name">supme</div>
          <div class="profile-card__txt"><strong>재미있는 설문조사로 해보는  <br></strong></div>
          <div class="profile-card-loc">
            
    
            <span class="profile-card-loc__txt">
          여행 MBTI
            </span>
          </div>

            <div class="profile-card-ctr">
              <form action="{% url 'survey:survey_q0' %}" method="post">
                {% csrf_token %}
                <button class="profile-card__button button--orange" type="submit" id="survey" name="start" value="start">
                  좌충우돌 우주여행 시작하기
                </button>
              </form>
            </div>

          <!-- <script>
            function forceSubmit(){
                document.forms[0].submit();
            }
          </script> -->
        </div>      
      </div>
      <script src="/static/survey/js/survey.js"></script>
</body>
</html>

survey/templates/survey/survey_q1.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
    <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey1.jpg" alt="profile card">
          </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">첫번째 질문</div>
            <div class="profile-card__txt"><strong>일론 머스크의 공짜 우주여행에 당첨되었다.<br></strong></div>
            <div class="profile-card-loc">
              <span class="profile-card-loc__icon">
                <!-- <svg class="icon">
                  <use xlink:href="#icon-location"></use>
                </svg> -->
              </span>
      
              <span class="profile-card-loc__txt">
                당신의 우주여행 선택지는?
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_q1' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="moon" name="where" value="moon">달</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="mars" name="where" value="mars">화성</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="blackhole" name="where" value="black_hole">우주 정거장</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="space_station" name="where" value="space_station">블랙홀</button>
                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>

      </div>


      <script src="/static/survey/js/survey.js"></script>

</body>
</html>

survey/templates/survey/survey_q10.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
  <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey3.jpg" alt="profile card">
                    </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">열번째 질문</div>
            <div class="profile-card__txt"><strong>일론머스크가 당신과 교신을 시도했다.<br> 당신은 드디어 가족의 품으로 돌아갈 수 있다. <br>하지만 이곳에 살아보니 외계인이 도움도 주고 꽤 살만하다. <br></strong></div>
            <div class="profile-card-loc">
              <span class="profile-card-loc__icon">
                <!-- <svg class="icon">
                  <use xlink:href="#icon-location"></use>
                </svg> -->
              </span>
      
              <span class="profile-card-loc__txt">
                당신은 이곳에서 살겠는가?
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_q10' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="yes" name="stay" value="yes">이곳에 머물러 제 2의 인생을 꿈꿔본다.</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="no" name="stay" value="no">그리운 내 집으로 돌아간다.</button>
                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>
      </div>

      <script src="/static/survey/js/survey.js"></script>

</body>
</html>

survey/templates/survey/survey_q11.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
  <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey10.jpg" alt="profile card">
          </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">당신의 외계인 친구는 누구일까요?</div>
            <div class="profile-card__txt"><strong><br></strong></div>
            <div class="profile-card-loc">
            
      
              <span class="profile-card-loc__txt">
                당신의 외계인 친구를 찾으면 알려드릴게요~ 버튼을 눌러 로그인 해주세요~
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_end' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="submit" onclick="forceSubmit()" id="login" name="send" value=" login">로그인</button>
                  
                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>
      </div>

      <script src="/static/survey/js/survey.js"></script>

</body>
</html>

survey/templates/survey/survey_q2.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
  <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey2.jpg" alt="profile card">

          </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">두번째 질문</div>
            <div class="profile-card__txt"><strong>우주여행을 가기 전에 당신의 신분을 체크하고 있다.<br></strong></div>
            <div class="profile-card-loc">
              <span class="profile-card-loc__icon">
                <!-- <svg class="icon">
                  <use xlink:href="#icon-location"></use>
                </svg> -->
              </span>
      
              <span class="profile-card-loc__txt">
                당신의 성별은?
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_q2' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="male" name="gender" value="M">남성</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="female" name="gender" value="W">여성</button>
                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>
      </div>

      <script src="/static/survey/js/survey.js"></script>

</body>
</html>

survey/templates/survey/survey_q3.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
  <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey3.jpg" alt="profile card">          </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">세번째 질문</div>
            <div class="profile-card__txt"><strong>우주여행을 가기 전에 당신의 신분을 체크하고 있다.<br></strong></div>
            <div class="profile-card-loc">
              <span class="profile-card-loc__icon">
                <!-- <svg class="icon">
                  <use xlink:href="#icon-location"></use>
                </svg> -->
              </span>
      
              <span class="profile-card-loc__txt">
                당신의 나이는 몇살인가?
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_q3' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="10s" name="age" value="10s">10대</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="20s" name="age" value="20s">20대</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="30s" name="age" value="30s">30대</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="40s" name="age" value="40s">40대</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="50s" name="age" value="50s">50대 이상</button>

                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>
      </div>

      <script src="/static/survey/js/survey.js"></script>

</body>
</html>

survey/templates/survey/survey_q4.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
    
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
  <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey4.jpg" alt="profile card">          
          </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">네번째 질문</div>
            <div class="profile-card__txt"><strong>우주여행이 시작되었다. 지구궤도를 돌파하려는 순간,<br>우주왕복선에 문제가 발생하였다.<br></strong></div>
            <div class="profile-card-loc">
              <span class="profile-card-loc__icon">
                <!-- <svg class="icon">
                  <use xlink:href="#icon-location"></use>
                </svg> -->
              </span>
      
              <span class="profile-card-loc__txt">
                당신은 비상탈출을 할 것인가?
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_q4' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="escape" name="disposition" value="escape">비상탈출을 시도한다</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="wait" name="disposition" value="wait">기장의 지시를 따른다</button>
                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>
      </div>

      <script src="/static/survey/js/survey.js"></script>

</body>
</html>

survey/templates/survey/survey_q5.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
  <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey5.jpg" alt="profile card">          
          </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">다섯번째 질문</div>
            <div class="profile-card__txt"><strong>탈출에 성공하였다. <br>  낙하산으로 내려가는동안두개의 육지가 보인다.<br></strong></div>
            <div class="profile-card-loc">
              <span class="profile-card-loc__icon">
                <!-- <svg class="icon">
                  <use xlink:href="#icon-location"></use>
                </svg> -->
              </span>
      
              <span class="profile-card-loc__txt">
                당신은 어떤 곳을 선택하겠는가?
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_q5' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="island" name="site" value="island">사면이 바다인 무인도</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="land" name="site" value="land">산으로 뒤덮힌 육지</button>
                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>
      </div>

      <script src="/static/survey/js/survey.js"></script>

</body>
</html>

survey/templates/survey/survey_q6.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href= "{% static 'survey/css/stylez.css' %}">
    <title>supme survey</title>
    <style>
      #survey-credit {
        display: flex;
        align-self: flex-end;
        font-size: x-small;
      }
    </style>
</head>
<body id="page-top" background="{% static 'survey/assets/supme-space.jpg' %}">
  <div class="wrapper">
        <div class="profile-card js-profile-card">
          <div class="profile-card__img">
            <img src="/static/survey/assets/survey6.jpg" alt="profile card">          
          </div>
      
          <div class="profile-card__cnt js-profile-cnt">
            <div class="profile-card__name">여섯번째 질문</div>
            <div class="profile-card__txt">사람이 없는 곳에서 우연히 당신은 외계생물체를 발견하였다. 그도 오랜시간 혼자였는지 나를 반기며 자신의 집을 소개해주려 한다.<br></div>
            <div class="profile-card-loc">
              <span class="profile-card-loc__icon">
                <!-- <svg class="icon">
                  <use xlink:href="#icon-location"></use>
                </svg> -->
              </span>
      
              <span class="profile-card-loc__txt">
                당신이 소개받은 집은 어떤 집인가??
              </span>
            </div>

              <div class="profile-card-ctr">
                <form action="{% url 'survey:survey_q6' %}" method="post">
                  {% csrf_token %}
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="cottage" name="house" value="cottage">오두막집</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="mordern" name="house" value="mordern">모던한 집</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="emotion" name="house" value="emotion">감성적인 집</button>
                  <button class="profile-card__button button--orange" type="radio" onclick="forceSubmit()" id="camping" name="house" value="camping">텐트</button>
                </form>
              </div>

            <script>
              function forceSubmit(){
                  document.forms[0].submit();
              }
            </script>
          </div>      
        </div>
      </div>

      <script src="/static/survey/js/survey.js"></script>

</body>
</html>