config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("", lambda x: redirect("/home/")),
    path('admin/', admin.site.urls),
    path('mypage/', include('mypage.urls')),
    path('survey/', include('survey.urls')),
    path('travelbox/', include('travelbox.urls')),
    # path('accounts/naver/login/', lambda request:redirect("/")),
    path('accounts/', include('allauth.urls')),
    path('accounts/social/login/cancelled/', lambda request: redirect("mypage/login/")),
    path('accounts/social/login/error/', lambda request: redirect("mypage/login/")),
    path('home/', include("home.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

mypage/urls.py
from django.urls import path
from mypage import views

app_name = 'mypage'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signup-add-info/', views.signup_add_info, name='signup_add_info'),
    path('select-travel/', views.select_travel, name='select_travel'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path("update/",views.update, name="update"),

]

travelbox/urls.py
from django.urls import path

from travelbox import views


app_name='travelbox'

urlpatterns = [
    # path("create/", views.create, name="create"),
    path("create/<int:selection_id>/", views.create, name="create_tmp"),
    path('read/<int:post_id>/', views.read, name='read_box'),
    path('read-all/', views.read_all, name='read_all'),
    path('update/<int:post_id>/', views.box_update, name='box_update'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('weather/', views.weather, name='weather'),
    path('travelbox/<int:post_id>/', views.travelbox, name='travelbox'),
    # path('travelbox/<str:travel_box_user>', views.travelbox, name='travelbox'),



]

travelbox/forms.py
from django.forms import ModelForm, TextInput
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={'class' : 'input', 'placeholder' : 'City Name'}),
        } #updates the input class to have the correct Bulma class and placeholder

travelbox/views.py
from time import timezone
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.http import HttpResponseRedirect
from mypage.models import Select
from django.utils import timezone

from travelbox.models import *
import requests
from .forms import CityForm

# Create your views here.

# def create(request, selection_id):
#     target_selection = Select.objects.get(id=selection_id)
#     # target_selection.selector.for_user
#     if request.method == 'GET':
#         return render(request, 'travelbox/box_create.html', context={
#             "selection": target_selection
#         })
#     elif request.method =='POST':
#         mk_box = Travel_box()
       
#         # mk_box.id = request.POST['id']
#         mk_box.travel_box_user = request.POST.get(user=target_selection.selector.for_user)

#         #### 우리가 travelbox 제작 ####
#         mk_box.sub_title = request.POST.get('sub_title')
#         mk_box.script = request.POST.get('script')
#         mk_box.place_name = request.POST.get("place_name")
#         mk_box.activity = request.POST.get('activity')
#         mk_box.accomdation = request.POST.get('accomdation')
#         mk_box.addr_accomdation = request.POST.get('addr_accomdation')
#         mk_box.food = request.POST.get('food')      
#         mk_box.sightseeing = request.POST.get('sightseeing')      
#         # mk_box.sightseeing_addr_link = request.POST.get('sightseeing_addr_link')      
#         mk_box.traffic = request.POST.get('traffic')

#         ### 장소 이미지 ###
#         if request.FILES.get("image_head"):          
#             mk_box.image_head = request.FILES['image_head']
        
#         ### 미션 이미지 ###
#         if request.FILES.get("image_1"):          
#             mk_box.image_1 = request.FILES['image_1']
#         if request.FILES.get("image_2"):  
#             mk_box.image_2 = request.FILES['image_2']
#         if request.FILES.get("image_3"):  
#             mk_box.image_3 = request.FILES['image_3']

#         ### 숙소, 음식, 액티비티, 볼거리 이미지 ###
#         if request.FILES.get("image_accomdation"):          
#             mk_box.image_accomdation = request.FILES['image_accomdation']
#         if request.FILES.get("image_food"):          
#             mk_box.image_food = request.FILES['image_food']
#         if request.FILES.get("image_activity"):          
#             mk_box.image_activity = request.FILES['image_activity']
#         if request.FILES.get("image_sightseeing"):          
#             mk_box.image_sightseeing = request.FILES['image_sightseeing']

#         ### 우리가 장소를 선택안하는 문제 방지 ###
#         if mk_box.place_name == "none":
#             return redirect("travelbox:create", selection_id)  
#         mk_box.save()
           
#         return redirect("travelbox:home")


### travel box 만들기 ###
def create(request, selection_id):
    target_selection = Select.objects.get(id=selection_id)
    if request.method == 'GET':
        return render(request, 'travelbox/box_create.html', context={
            "selection": target_selection
        })
    elif request.method =='POST':
        mk_box = Travel_box()
       
        # mk_box.id = request.POST['id']
        mk_box.travel_box_user = target_selection.selector.for_user
        mk_box.travel_box_id = target_selection
        #### 우리가 travelbox 제작 ####
        mk_box.sub_title = request.POST.get('sub_title')
        mk_box.script = request.POST.get('script')
        mk_box.place_name = request.POST.get("place_name")

        mk_box.activity_1 = request.POST.get('activity_1')
        mk_box.activity_2= request.POST.get('activity_2')
        mk_box.activity_3 = request.POST.get('activity_3')
        
        mk_box.addr_activity_1 = request.POST.get('addr_activity_1')
        mk_box.addr_activity_2= request.POST.get('addr_activity_2')
        mk_box.addr_activity_3 = request.POST.get('addr_activity_3')

        mk_box.accomdation_1 = request.POST.get('accomdation_1')
        mk_box.accomdation_2 = request.POST.get('accomdation_2')
        mk_box.accomdation_3 = request.POST.get('accomdation_3')
       
        mk_box.addr_accomdation_1 = request.POST.get('addr_accomdation_1')
        mk_box.addr_accomdation_2 = request.POST.get('addr_accomdation_2')
        mk_box.addr_accomdation_3 = request.POST.get('addr_accomdation_3')

        mk_box.food_1 = request.POST.get('food_1')      
        mk_box.food_2 = request.POST.get('food_2')      
        mk_box.food_3 = request.POST.get('food_3')   
        
        mk_box.addr_food_1 = request.POST.get('addr_food_1')      
        mk_box.addr_food_2 = request.POST.get('addr_food_2')      
        mk_box.addr_food_3 = request.POST.get('addr_food_3')   

        mk_box.sightseeing_1 = request.POST.get('sightseeing_1')      
        mk_box.sightseeing_2 = request.POST.get('sightseeing_2')      
        mk_box.sightseeing_3 = request.POST.get('sightseeing_3')      
        
        mk_box.addr_sightseeing_1 = request.POST.get('addr_sightseeing_1')      
        mk_box.addr_sightseeing_2 = request.POST.get('addr_sightseeing_2')      
        mk_box.addr_sightseeing_3 = request.POST.get('addr_sightseeing_3')      
        

        mk_box.traffic = request.POST.get('traffic')
        mk_box.create_date = timezone.now()

        ### 장소 이미지 ###
        if request.FILES.get("image_head"):          
            mk_box.image_head = request.FILES['image_head']
        
        ### 미션 이미지 ###
        if request.FILES.get("image_1"):          
            mk_box.image_1 = request.FILES['image_1']
        if request.FILES.get("image_2"):  
            mk_box.image_2 = request.FILES['image_2']
        if request.FILES.get("image_3"):  
            mk_box.image_3 = request.FILES['image_3']

        ### 숙소, 음식, 액티비티, 볼거리 이미지 ###
        if request.FILES.get("image_accomdation_1"):          
            mk_box.image_accomdation_1 = request.FILES['image_accomdation_1']
        if request.FILES.get("image_accomdation_2"):          
            mk_box.image_accomdation_2 = request.FILES['image_accomdation_2']
        if request.FILES.get("image_accomdation_3"):          
            mk_box.image_accomdation_3 = request.FILES['image_accomdation_3']

        if request.FILES.get("image_food_1"):          
            mk_box.image_food_1 = request.FILES['image_food_1']
        if request.FILES.get("image_food_2"):          
            mk_box.image_food_2 = request.FILES['image_food_2']
        if request.FILES.get("image_food_3"):          
            mk_box.image_food_3 = request.FILES['image_food_3']

        if request.FILES.get("image_activity_1"):          
            mk_box.image_activity_1 = request.FILES['image_activity_1']
        if request.FILES.get("image_activity_2"):          
            mk_box.image_activity_2 = request.FILES['image_activity_2']
        if request.FILES.get("image_activity_3"):          
            mk_box.image_activity_3 = request.FILES['image_activity_3']

        if request.FILES.get("image_sightseeing_1"):          
            mk_box.image_sightseeing_1 = request.FILES['image_sightseeing_1']
        if request.FILES.get("image_sightseeing_2"):          
            mk_box.image_sightseeing_2 = request.FILES['image_sightseeing_2']
        if request.FILES.get("image_sightseeing_3"):          
            mk_box.image_sightseeing_3 = request.FILES['image_sightseeing_3']
        
        if request.FILES.get("traffic_road"):          
            mk_box.traffic_road = request.FILES['traffic_road']





        ### 우리가 장소를 선택안하는 문제 방지 ###
        if mk_box.place_name == "none":
            return redirect("travelbox:create")   
        mk_box.save()
        # print(selection_id)
        # return render(request, 'travelbox/box_create.html')
        return redirect("travelbox:read_all")


 ### 해당 유저의 travel box를 우리가 잘 만들었는지 우리측 확인용(travel box error 여부 확인용) ###
def read(request, post_id):

    post = Travel_box.objects.get(id=post_id)

    context = {
        'post': post,
        
        
    }

    return render(request, 'travelbox/read_box.html', context)


### 우리가 만든 travel box들에 대한 리스트 ###
def read_all(request):
    
    post_list = Travel_box.objects.all()

    context = {
        'posts': post_list
        
    }

    return render(request, 'travelbox/read_box_list.html', context)

### travel box 수정 ###
def box_update(request, post_id):
    if request.method =='GET':
            
        post =Travel_box.objects.get(id = post_id)
        context = {
            'post' : post
        }
        return render(request, "travelbox/box_update.html", context)


    elif request.method =='POST':
        target_post = Travel_box.objects.get(id = post_id)
        target_post.place_name = request.POST['place_name']
        target_post.traffic = request.POST['traffic']
        target_post.accomdation = request.POST['accomdation']
        target_post.food = request.POST['food']
        target_post.activity = request.POST['activity']
        target_post.sightseeing = request.POST['sightseeing']
        if request.FILES.get("image_1"):
            print('ok')
            target_post.image_1 = request.FILES['image_1']
        if request.FILES.get("image_2"):
            print('ok')
            target_post.image_2 = request.FILES['image_2']
        if request.FILES.get("image_3"):
            print('ok')
            target_post.image_3 = request.FILES['image_3']
        target_post.save()
        
        


        return HttpResponseRedirect('/travelbox/read-all/')

### travel box 자체를 삭제하기 ###
def delete(request, post_id):
    if request.method == "GET":
        post = Travel_box.objects.get(id = post_id)
        context = {
            'post' : post
        }
        return render(request, 'travelbox/box_delete.html', context)
    elif request.method == 'POST':
        delete_post = Travel_box.objects.get(id = post_id)
        delete_post.delete()

travelbox/templates/travelbox/box_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<p>
    <h1>Travel box</h1>

    <form action="{% url 'travelbox:create_tmp' selection.id %}" id="post-write" method="post" enctype="multipart/form-data">
    {% csrf_token %}
     <!-- 장소: <input type="text" name="place_name"><br>
     교통: <input type="text" name="traffic"><br>
     숙소: <input type="text" name="accomdation"><br>
     음식: <input type="text" name="food"><br>
     경치: <input type="text" name="sightseeing"><br>
     액티비티: <input type="text" name="activity"><br>
      -->

      <label for="place_name">장소:</label>
      <select name="place_name" >
        <option value="none">선택</option>
        <option value="영월">영월</option>
        <option value="철원">철원</option>
        <option value="군산">군산</option>
        <option value="삼척">삼척</option>
        <option value="문경">문경</option>
        <option value="철원">태안</option>
      </select>
      <br><br>
      
      <label for="traffic">교통수단:</label>
      <select name="traffic" >
        <option value="none">선택</option>
        <option value="자차">자차</option>
        <option value="고속버스">고속버스</option>
        <option value="기차">기차</option>
      </select>
      교통_지도<input type="file" name="traffic_road"><br>
      <br><br>
      숙소_1: <input type="text" name="accomdation_1"><br>
      숙소_이미지_1: <input type="file" name="image_accomdation_1"><br>
      숙소_링크_1: <input type="text" name="addr_accomdation_1"><br>
      <br><br>
      숙소_2: <input type="text" name="accomdation_2"><br>
      숙소_이미지_2: <input type="file" name="image_accomdation_2"><br>
      숙소_링크_2: <input type="text" name="addr_accomdation_2"><br>
      <br><br>
      숙소_3: <input type="text" name="accomdation_3"><br>
      숙소_이미지_3: <input type="file" name="image_accomdation_3"><br>
      숙소_링크_3: <input type="text" name="addr_accomdation_3"><br>
      <br><br>
      음식_1: <input type="text" name="food_1"><br>
      음식_이미지_1: <input type="file" name="image_food_1"><br>
      음식_주소_1: <input type="text" name="addr_food_1"><br>
      <br><br>
      음식_2: <input type="text" name="food_2"><br>
      음식_이미지_2: <input type="file" name="image_food_2"><br>
      음식_주소_2: <input type="text" name="addr_food_2"><br>
      <br><br>
      음식_3: <input type="text" name="food_3"><br>
      음식_이미지_3: <input type="file" name="image_food_3"><br>
      음식_주소_3: <input type="text" name="addr_food_3"><br>
      <br><br>
      경치_1: <input type="text" name="sightseeing_1"><br>
      경치_주소_1: <input type="text" name="addr_sightseeing_1"><br>
      경치_이미지_1: <input type="file" name="image_sightseeing_1"><br>
      <br><br>
      경치_2: <input type="text" name="sightseeing_2"><br>
      경치_주소_2: <input type="text" name="addr_sightseeing_2"><br>
      경치_이미지_2: <input type="file" name="image_sightseeing_2"><br>
      <br><br>
      경치_3: <input type="text" name="sightseeing_3"><br>
      경치_주소_3: <input type="text" name="addr_sightseeing_3"><br>
      경치_이미지_3: <input type="file" name="image_sightseeing_3"><br>
      <br><br>
      액티비티: <input type="text" name="activity_1"><br>
      액티비티_이미지: <input type="file" name="image_activity_1"><br>    
      액티비티_주소: <input type="text" name="addr_activity_1"><br>
      <br><br>
      액티비티: <input type="text" name="activity_2"><br>
      액티비티_이미지: <input type="file" name="image_activity_2"><br>    
      액티비티_주소: <input type="text" name="addr_activity_2"><br>
      <br><br>
      액티비티: <input type="text" name="activity_3"><br>
      액티비티_이미지: <input type="file" name="image_activity_3"><br>    
      액티비티_주소: <input type="text" name="addr_activity_3"><br>
      <br><br>
      
      부제목: <input type="text" name="sub_title"><br>
      설명: <input type="text" name="script"><br>
      <br><br>



     <div>
        지역사진   <input type="file" name="image_head"><br>
        미션사진_1 <input type="file" name="image_1"><br>
        미션사진_2 <input type="file" name="image_2"><br>
        미션사진_3 <input type="file" name="image_3"><br>
     </div>
     <br><br>
     
     <input type="submit" value="submit" >
    </form>

    
</body>
</html>

travelbox/templates/travelbox/box_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <p>Delete: {{post.title}}?</p>
    <form action="{% url 'travelbox:delete' post.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="yes">     
    </form>
    <form action="{% url 'travelbox:read_all'%}" method="get">
        {% csrf_token %}
        <input type="submit" value="no">     
    </form>
   
    
</body>
</html>

travelbox/templates/travelbox/box_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travelbox Update</title>
</head>
<body>
   <form action="{% url 'travelbox:box_update' post.id %}" id="post-edit" method="post" enctype="multipart/form-data">
       {% csrf_token %}
    장소: <input type="text" name="place_name" value="{{post.place_name}}"><br>
    교통: <input type="text" name="traffic" value="{{post.traffic}}"><br>
    숙소: <input type="text" name="accomdation" value="{{post.accomdation}}"><br>
    음식: <input type="text" name="food" value="{{post.food}}"><br>
    경치: <input type="text" name="sightseeing" value="{{post.sightseeing}}"><br>
    액티비티: <input type="text" name="activity" value="{{post.activity}}"><br>
    부제목: <input type="text" name="sub_title" value="{{post.sub_title}}"><br>
    설명: <input type="text" name="script" value="{{post.script}}"><br><br><br>
    <div>
        {% if post.image_head %}
                <div style="width: 250px;">
                    대표 사진<img src="{{ post.image_head.url }}" alt="post image_head" style="width: 100%;">
                    <input type="file" name="image_head" id="post-edit"><br>
                </div>
        {% endif %}
        <br>
        {% if post.image_1 %}
                <div style="width: 250px;">
                    미션사진_1<img src="{{ post.image_1.url }}" alt="post image_1" style="width: 100%;">
                    <input type="file" name="image_1" id="post-edit"><br>
                </div>
        {% endif %}
        <br>
        {% if post.image_2 %}
                <div style="width: 250px;">
                    미션사진_2<img src="{{ post.image_2.url }}" alt="post image_2" style="width: 100%;">
                    <input type="file" name="image_2" id="post-edit"><br>
                </div>
        {% endif %}
        <br>
        {% if post.image_3 %}
                <div style="width: 250px;">
                    미션사진_3<img src="{{ post.image_3.url }}" alt="post image_3" style="width: 100%;">
                    <input type="file" name="image_3" id="post-edit"><br>
                </div>
        {% endif %}
       
        
    </div>
    <input type="submit" value="submit" onclick="alert('업데이트 완료')">
   </form>

   <div>
    <a href="{% url 'travelbox:read_all'%}" style="width: 300px">Go back</a>
    </div>

   
</body>
</html> 

travelbox/templates/travelbox/mybox_submit_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .container {
            width: 100vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>전송중</h1>
    </div>
    <script>
        window.addEventListener("load", () => {
            {% if success %}
            alert("success!");
            location.href = '{% url "mypage:dashboard" %}'
            {% else %}
            alert("fail!");
            location.href = '{% url "travelbox:travelbox" post.id %}';
            {% endif %}
        });
    </script>
</body>
</html>

travelbox/templates/travelbox/read_box.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Read </title>
</head>
<body>
    <h1>{{post.id}}</h1>
    {% if post.image_head %}
    <div style="width: 250px;">
        <img src="{{ post.image_head.url }}" alt="post image_head" style="width: 100%;">
    </div>
    {% endif %}

    <h2>{{post.place_name}}</h2>
    <h3>{{post.sub_title}}</h3>
    <h4>{{post.script}}</h4>
    <p>{{post.traffic}}</p>
    <p>{{post.accomdation}}</p>
    <p>{{post.food}}</p>
    <p>{{post.activity}}</p>
    <p>{{post.sightseeing}}</p>
    <br><br><br>
    {% if post.image_1 %}
    <div style="width: 250px;">
        <img src="{{ post.image_1.url }}" alt="post image_1" style="width: 100%;">
    </div>
    {% endif %}
    {% if post.image_2 %}
    <div style="width: 250px;">
        <img src="{{ post.image_2.url }}" alt="post image_2" style="width: 100%;">
    </div>
    {% endif %}

    {% if post.image_3 %}
    <div style="width: 250px;">
        <img src="{{ post.image_3.url }}" alt="post image_3" style="width: 100%;">
    </div>
    {% endif %}
    <br><br>

    <div>
        <a href="{% url 'travelbox:box_update' post.id %}" style="width: 300px">Edit</a>
    </div>
    <div>
        <a href="{% url 'travelbox:delete' post.id %}">delete</a>
    </div>
    <div>
    <a href="{% url 'travelbox:read_all'%}">Go back</a>
    </div>

     <!-- 임시===== -->
     <div>
        <a href="{% url 'travelbox:travelbox' post.id%}">My Box_test2</a>
        </div>
    
    
    </body>
</html>

travelbox/templates/travelbox/read_box_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Read all</title>
</head>
<body>
    {% if posts %}
    <ul>
        {% for post in posts %}
        <li><a href="{% url 'travelbox:read_box' post.id %}">{{ post}}</a></li>
        {% empty%}
        <li>작성된 글이 없습니다.</li>
        {% endfor  %}
    </ul>
    {% else %}
    <!-- 이건 html주석입니다 -->
    {#이건 장고 템플릿의 주석입니다.#}
    <p>작성된 글이 없습니다.</p>
    {% endif %}
   

</body>
</html>

travelbox/templates/travelbox/weather.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>What's the weather like?</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>
<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
    <div class="field has-addons">
        <div class="control is-expanded">
            {{ form.name }}
        </div>
        <div class="control">
            <button class="button is-info">
                Add City
            </button>
        </div>
    </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% for weather in weather_data %}
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ weather.city }}</span>
                                        <br>
                                        <span class="subtitle">{{ weather.temperature }}° C</span>
                                        <br> {{ weather.description }}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>
</html>