config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("", lambda x: redirect("/home/")),
    path('admin/', admin.site.urls),
    path('mypage/', include('mypage.urls')),
    path('survey/', include('survey.urls')),
    path('travelbox/', include('travelbox.urls')),
    # path('accounts/naver/login/', lambda request:redirect("/")),
    path('accounts/', include('allauth.urls')),
    path('accounts/social/login/cancelled/', lambda request: redirect("mypage/login/")),
    path('accounts/social/login/error/', lambda request: redirect("mypage/login/")),
    path('home/', include("home.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

mypage/urls.py
from django.urls import path
from mypage import views

app_name = 'mypage'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signup-add-info/', views.signup_add_info, name='signup_add_info'),
    path('select-travel/', views.select_travel, name='select_travel'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path("update/",views.update, name="update"),

]

mypage/models.py
from multiprocessing.sharedctypes import Value
from django.db import models
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    name = models.CharField(max_length=32)
    phone_number = models.CharField(max_length=32)
    GENDER =[
        ('M', '남성'),
        ('W', '여성'),
    ]
    gender = models.CharField(max_length=4, choices=GENDER)
    email = models.CharField(max_length=32)
    age = models.CharField(max_length=16)
    # alien_type = models.CharField(max_length=32)

    alien_type = models.ImageField(
        upload_to = "static/alien/%y"
    )
    alien_name = models.CharField(max_length=32)
    alien_content = models.TextField()
    for_user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)


class Select(models.Model):
    selector = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    people = models.IntegerField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    TRAVEL_PURPOSE=[
        ('힐링', '힐링'),
        ('아웃도어', '아웃도어'),
        ('맛집투어', '맛집투어'),
        ('자연감상', '자연감상'),
    ]

    PLACE_START = [
        ('강동구', '강동구'),
        ('강남구', '강남구'),
        ('강북구', '강북구'),
        ('강서구', '강서구'),
    ]

    SELECT_STATE = [
        ("preparing", "여행 준비 중"),
        ("prepared", "여행 준비 끝"),
        ("on_travel", "여행 중"),
        ("finished", "여행 완료"),
    ]
    travel_purpose = models.CharField(max_length=30, choices=TRAVEL_PURPOSE, default='자연감상')
    selection_state = models.CharField(max_length=32, choices=SELECT_STATE, default=SELECT_STATE[0][0])
    def state_name(self):
        for state in self.SELECT_STATE:
            if state[0] == self.selection_state:
                return state[1]
    place_start = models.CharField(max_length=10, choices=PLACE_START, default='강동구')
    create_date = models.DateTimeField()

    def __str__(self):
        return self.selector.for_user.username

mypage/views.py
from wsgiref.handlers import format_date_time
from django.shortcuts import render, redirect, get_object_or_404
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth.models import User
from django.contrib import auth
from mypage.models import Profile, Select
from travelbox.models import Travel_box, GetPic
from allauth.socialaccount import models
from django.utils import timezone
from survey.models import SurveyQuestion
from django.db.utils import OperationalError

from datetime import datetime


# Create your views here.

def index(request):
    return render(request, 'mypage/index.html')

### LOGIN ###
def login(request):
    context ={}
    if request.method == "POST":
        if request.POST.get('username') and request.POST.get('password'):
            user = auth.authenticate(
                request,
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )
            if user is not None:
                auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect("mypage:dashboard")
            else:
                context['error'] = '아이디와 비밀번호를 다시 확인해주세요'
        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해주세요'
    return render(request, 'mypage/login.html', context)


### LOGOUT ###
def logout(request):
    if request.method == "POST":
        auth.logout(request)
    return redirect('home:home')


### SIGN UP ###
def signup(request):
    context = {}
    if request.method == "POST":
        if(request.POST.get('username') and
            request.POST.get('password') and
            request.POST.get('password') == request.POST.get('password_check')):
            if User.objects.filter(username=request.POST.get('username')).exists():
                return redirect("mypage:login")
            
            new_user = User.objects.create_user(
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )

            # auth.login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect("mypage:signup_add_info")
        else:
            context["error"] = '올바르지 않은 정보입니다.'
    
    return render(request, 'mypage/sign_up.html')



####SIGN UP ADD INFO ####
def signup_add_info(request):
    if not request.user.is_authenticated:
        return redirect("mypage:login")

    if request.method == "GET":
        return signup_add_info_view(request)

    #### 홈페이지를 통해 회원 가입한 user의 추가 정보 ####
    # Form Element의 요청을 통해 받은 데이터 저장
    if request.method == "POST":
        new_profile = Profile()
        new_profile.gender = request.POST.get('gender')
        new_profile.name = request.POST.get('name')
        new_profile.phone_number = request.POST.get('phone_number')
        new_profile.age = request.POST.get('age')
        new_profile.email = request.POST.get('email')
        new_profile.for_user = request.user
        new_profile.save()
        return redirect('mypage:dashboard')
        # return redirect('mypage:dashboard', username = new_profile.for_user)



def signup_add_info_view(request):
    #### social login user profile ####
    context = {}
    survey_uid = request.COOKIES.get("supme-survey-id")
    user_gender = None
    user_age = None
    user_email = None

    # 소셜 계정이 있다면
    if SocialAccount.objects.filter(user=request.user).exists():
        # 소셜계정 가져오기
        social_user = SocialAccount.objects.get(user=request.user)
        # 소셜 계정의 성별 정보를 임시 저장
        user_gender = social_user.extra_data.get('gender')
        
        # 소셜 계정의 나이 정보를 임시 저장
        user_age = social_user.extra_data.get('age')
        if user_age is None:
            user_age = social_user.extra_data.get('age_range')

        # 소셜 계정의 이메일 정보를 임시 저장
        user_email = social_user.extra_data.get('email')


    # 회수한 성별 정보 있는지 확인 후 전달 (context["M"] or context["W"])
    if user_gender is None:
        user_gender_list = SurveyQuestion.objects.filter(survey_uid=survey_uid)
        if user_gender_list.exists():
            try:
                user_gender_list2=user_gender_list.order_by("-pk")[0]
                user_gender = user_gender_list2.question2
            except OperationalError:
                pass

    if user_gender is not None:
        if user_gender == "M":
            context["M"] = True
        elif user_gender == "W":
            context["W"] = True

    # 회수한 나이 정보 있는지 확인 후 전달 (context["age"])
    if user_age is not None:
        context["age"] = user_age

    # 회수한 이메일 정보 있는지 확인 후 전달 (context["email"])
    if user_email is not None:
        context["email"] = user_email

    # (소셜 계정 및 Question2에서) 받은 데이터와 함깨 HTML전달
    return render(request, 'mypage/signup_add_info.html', context)




def dashboard(request):
    if request.user.is_authenticated:
        profile = Profile.objects.all().filter(for_user=request.user)
        box_viewer = Travel_box.objects.all().filter(travel_box_user=request.user)

        context = {}

        if len(profile) < 1:
            return redirect("mypage:signup_add_info")
        else:
            profile = profile[0]
            current_select_list = Select.objects.filter(selector=profile).exclude(selection_state="finished")

            ### 여행 의뢰 할 수 있도록 만드는 버튼 ####
            can_select = not current_select_list.exists()
            if not can_select:
                current_select = current_select_list.order_by("-pk")[0]
                context[current_select.selection_state] = True
           
            #### 유저의 해당 travelbox 보기 ####
            if box_viewer:
                box_viewer = box_viewer.order_by("-pk")[0]
                
                #### 유저가 사진 올린거 사진첩에 띄우기 ####
                getpics = GetPic.objects.filter(box_id=box_viewer.id)
                if getpics.exists():
                    album = getpics.order_by("-pk")[0]
                    context.update({"album": album})
            
            context.update({
                "profile": profile,
                "can_select": can_select,
                "box_viewer": box_viewer,
            })
            return render(request, 'mypage/dashboard.html', context)

    return redirect("home:home")
    

def select_travel(request):
    profile = get_object_or_404(Profile, for_user=request.user)
    print(request.POST.get("daterange"))
    daterange_raw = request.POST.get("daterange")
    date_start = daterange_raw.split(" - ")[0]
    date_end = daterange_raw.split(" - ")[1]

    date_start = datetime.strptime(date_start, "%m/%d/%Y")
    date_end = datetime.strptime(date_end, "%m/%d/%Y")

    select = Select(
        selector=profile, 
        people=request.POST.get('people'), 
        start_date=date_start,
        end_date=date_end,
        travel_purpose=request.POST.get('travel_purpose'), 
        place_start=request.POST.get('place_start'), 
        create_date=timezone.now()
        )
    select.save()
    return redirect("mypage:dashboard")


def update(request):
    if request.method == "GET":
        return render(request, "mypage/profile_update.html")
    elif request.method == "POST":
        profile_update = Profile.objects.get(for_user=request.user)
        profile_update.name = request.POST.get('name')
        profile_update.phone_number = request.POST.get('phone_number')
        profile_update.email = request.POST.get('email')
        profile_update.save()
    return redirect("mypage:dashboard")

mypage/templates/mypage/create_add_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>Signup Plus</h1>
    <form action="{% url 'mypage:create_add_info' %}" method="post">
        {% csrf_token %}
        <input type="text" name="name" placeholder="이름"/><br>
        <input type="text" name="phone_number" placeholder="전화번호"/><br>

        
        <p>성별을 선택해주세요:</p>
        <div class="d-flex justify-content-between">
            <input type="radio" id="male" name="gender" value="M" {% if M %}checked{% endif %} />
            <label for="male">남성</label>
            <input type="radio" id="female" name="gender" value="W" {% if W %}checked{% endif %}/>
            <label for="female">여성</label><br>
        </div>
        <input type="text" name="age" placeholder="연령대" {% if age %}value="{{ age }}"{% endif %}/><br>
        <input type="email" name="email" placeholder="이메일" {% if email %}value="{{ email }}"{% endif %}/><br>
        <input type="submit" />
    </form>
    <form action="{% url 'mypage:logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="로그아웃" />
    </form>
</body>
</html>

mypage/templates/mypage/index.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
    <form action="/mypage/logout/" method="post">
        {% csrf_token %}
        <input type="submit" value="로그아웃" />
    </form>
    {% else %}
    <form action="/mypage/login/" method="get">
        <input type="submit" value="로그인" />
    </form>
    <form action="/mypage/signup/" method="get">
        <input type="submit" value="회원가입" />
    </form>
    <div class="d-flex justify-content-between">
        <div class="mb-3">
            <form action="{% provider_login_url 'naver' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="네이버">
            </form>
        </div>
        <div class="mb-3">
            <form action="{% provider_login_url 'kakao' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="카카오">
            </form>
        </div>
    </div>
    {% endif %}
</body>
</html>
   

mypage/templates/mypage/login-test.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="post" action="{% url 'mypage:login' %}">
        {% csrf_token %}
        <div>
            <label for="username"></label>
            <input id="username" type="text" name="username" placeholder="아이디">
        </div>
        <div>
            <label for="password"></label>
            <input id="password" type="password" name="password" placeholder="비밀번호">
        </div>
        <div>
            <button type="submit">로그인</button>
        </div>
    </form>
        <!-- social login  -->
        <div class="d-flex justify-content-between">
            <div class="mb-3">
                <form action="{% provider_login_url 'naver' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="네이버">
                </form>
            </div>
            <div class="mb-3">
                <form action="{% provider_login_url 'kakao' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="카카오">
                </form>
            </div>
            <div class="mb-3">
                <form action="/mypage/signup/" method="get">
                    <input type="submit" value="회원가입" />
                </form>
            </div>
        </div>
</body>
</html>

mypage/templates/mypage/profile_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="icon" type="image/x-icon" href="/static/landing/assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/landing/css/styles.css" rel="stylesheet" />
    
    <!-- profile card 관련 css -->
    <link rel="stylesheet" href= "/static/survey/css/style.css">
    <!-- Favicon -->
    <link href="/static/home/img/favicon.png" rel="icon">
    <title>Profile Edit</title>
</head>
<body background="/static/landing/assets/img/space.jpg" >
    <body id="page-top"  >
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark  fixed-top" style="background-color:#E2455A;" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">SUPME</span>
                <span class="d-none d-lg-block"><iframe src="https://giphy.com/embed/wPyDWwurn8XEWdR9ol" width="240"  frameBorder="0" class="giphy-embed img-fluid mx-auto mb-2" ></iframe></span>
                <!-- <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="assets/img/profile.jpg" alt="..." /></span> -->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'mypage:dashboard' %}">My Dashboard</a></li>
                    
                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- Profile-->
            <section class="resume-section" id="profile">
                <div class="resume-section-content">
                    <h2 class="mb-0" style="padding-left: 50px; padding-top: 30px;">
                        화성에서 온<br>
                        <span class="text-primary" style="color:#E2455A;">{{user.username}}의 업데이트</span>
                    </h2>
        
                    <br>

                    <div class="card text-center" style="margin-top:60px; opacity: 0.85;  padding-bottom: 50px;"   >

                        <div class="profil-contents" >
                            <form action="{% url 'mypage:update' %}" id="post-edit" method="post">
                                {% csrf_token %} 
                                <p style="font-size:20px; padding-top:20px; padding-bottom:30px;"> 정보를 모두 채워주세요 </p>
                                <span class="subheading mb-5" style="color:black; padding-left: 38px; font-size: 20px;">이름 <input style="margin-top:10px;" placeholder= '새로운 이름' type="text" name="name" value="{{ profile.name }}"></span><br>
                                <span class="subheading mb-5" style="color:black; font-size: 20px;">전화번호 <input style="margin-top:10px;" placeholder="010-1234-1234" type="text" name="phone_number" value="{{ profile.phone_number }}"></span><br>
                                <span class="subheading mb-5" style="color:black; padding-left: 19px; font-size: 20px;">이메일 <input style="margin-top:10px;" placeholder="OOOO@supme.co.kr" type="email" name="email" value="{{ profile.email }}"></span><br>
                                

                                
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button class="btn  me-md-2 profile-card__button button--orange" type="submit" style="color:white; text-decoration:none; margin-top: 50px; margin-left: 40px; margin-right: 40px; ">수정 완료</button>
                                </div>
                                
                            </form>
                        
                        </div>
                    </div>    
                </div>
            </section>
            <hr class="m-0" />

            <div class="container-xxl testimonial my-6 py-1 bg-dark wow zoomIn" data-wow-delay="1s" style="opacity:0.9;">
                <div class="container">
                    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                    <div class="col-md-4 d-flex align-items-center">
                        </a>
                        <span class="text-muted">&copy; 2022 SUPME</span>
                    </div>
                        <div >
                                <a class="me-3" href="https://www.facebook.com/"><i class="fab fa-facebook-f" ></i></a>
                                <a class="me-3" href="https://twitter.com/"><i class="fab fa-twitter" ></i></a>
                                <a class="me-3" href="https://www.instagram.com/_supme.travelbox/?hl=ko"><i class="fab fa-instagram"  ></i></a>
                                <a class="me-3" href="https://www.youtube.com/?gl=KR"><i class="fab fa-youtube" ></i></a>
                    </footer>
                </div>
            </div>

            
            
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/landing/js/scripts.js"></script>
    </body>

</body>
</html>

mypage/templates/mypage/sign_up-tmp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="icon" type="image/x-icon" href="/static/landing/assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/landing/css/styles.css" rel="stylesheet" />
    <title>Profile Edit</title>
</head>
<body>
    <body id="page-top"  background="/static/landing/assets/img/space.jpg">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark  fixed-top" style="background-color:orange;" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">화성에서온 첫사랑</span>
                <span class="d-none d-lg-block"><iframe src="https://giphy.com/embed/wPyDWwurn8XEWdR9ol" width="240"  frameBorder="0" class="giphy-embed img-fluid mx-auto mb-2" ></iframe></span>
                <!-- <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="assets/img/profile.jpg" alt="..." /></span> -->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#profile">다른페이지 이동링크</a></li>
                    
                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- Profile-->
            <section class="resume-section" id="profile">
                <div class="resume-section-content">
                    <h2 class="mb-0">
                        화성에서
                        <span class="text-primary" style="color:orange;">회원가입</span>
                    </h2>
                    <br>
                    <div class="profil-contents" >
                        <form method="post" action="{% url 'mypage:signup' %}">
                            <!-- 우리 회원가입 -->
                            {% csrf_token %}
                            <div>
                                <label for="username">아이디: </label>
                                <input class="subheading mb-5" style="color: black;" id="username" type="text" name="username" placeholder="아이디">
                            </div>
                            <div>
                                <label for="password">비밀번호: </label>
                                <input class="subheading mb-5" style="color: black;" id="password" type="password" name="password" placeholder="비밀번호">
                            </div>
                            <div>
                                <label for="password_check">비밀 번호 확인:</label>
                                <input class="subheading mb-5" style="color: black;" id="password_check" type="password" name="password_check" placeholder="비밀번호 확인">
                            </div>
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <button class="btn btn-primary me-md-2" type="submit">회원가입</button>
                            </div>
                        </form>  
                    </div>
                </div>
            </section>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/landing/js/scripts.js"></script>
    </body>

</body>
</html>

mypage/templates/mypage/sign_up_test.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <form method="post" action="{% url 'mypage:signup' %}">
        <!-- 우리 회원가입 -->
        {% csrf_token %}
        <div>
            <label for="username"></label>
            <input id="username" type="text" name="username" placeholder="아이디">
        </div>
        <div>
            <label for="password"></label>
            <input id="password" type="password" name="password" placeholder="비밀번호">
        </div>
        <div>
            <label for="password_check"></label>
            <input id="password_check" type="password" name="password_check" placeholder="비밀번호 확인">
        </div>
        <div>
            <button type="submit">회원가입</button>
        </div>
    </form>
</body>
</html>

mypage/templates/mypage/signup_add_info.html
{% extends "base.html" %}
{% block title %}회원정보입력{% endblock %}
{% block active_sign-up %}active{% endblock %}
{% block main %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>회원정보 입력</title>
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

   
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/style.css" rel="stylesheet">

</head>
<body>
    <main class="flex-shrink-0">
        <!-- Page content-->
        <section class="py-5">
            <div class="container px-5">
                <!-- Contact form-->
                <div class="bg-light rounded-3 py-5 px-4 px-md-5">
                    <div class="text-center mb-5">
                        <h1 class="fw-bolder">회원 정보 입력</h1>
                        <!-- <p class="lead fw-normal text-muted mb-0">We'd love to hear from you</p> -->
                    
                        <form action="{% url 'mypage:signup_add_info' %}" method="post">
                            {% csrf_token %}
                            <input style="margin-top:30px;" type="text" name="name" placeholder="이름"/><br>
                            <input style="margin-top:10px;" type="text" name="phone_number" placeholder="전화번호"/><br>

                            
                            <p style="font-size:18px; color:white; padding-top: 30px; ">성별을 선택해 주세요</p>
                            <div class="d-flex justify-content-center" style="padding:20px">
                                <input type="radio" id="male" name="gender" value="M" {% if M %}checked{% endif %} />
                                <label for="male" style="font-size:16px; color:white;">&nbsp;남 성&nbsp;&nbsp;</label>
                                <input type="radio" id="female" name="gender" value="W" {% if W %}checked{% endif %}/>
                                <label for="female" style="font-size:16px; color:white;">&nbsp;여 성</label><br>
                            </div>
                            <input style="margin-top:10px;" type="text" name="age" placeholder="연령대" {% if age %}value="{{ age }}"{% endif %}/><br>
                            <input style="margin-top:10px;" type="email" name="email" placeholder="이메일" {% if email %}value="{{ email }}"{% endif %}/><br>
                            <input style="margin-top:10px;"  type="submit" class="bbtn" />
                        </form>
                            <div class = >
                            <form action="{% url 'mypage:logout' %}" method="post">
                                {% csrf_token %}
                                <input style="margin-top:10px;" type="submit" value="로그아웃" class="bbtn" />
                            </form>
                        </div>


                        <!-- 제출/로그아웃 style css-->
                        <style>
                            .bbtn {
                                padding:5px 15px; 
                                background-color:#E2455A;
                                color:white; 
                                border:0 none;
                                cursor:pointer;
                                -webkit-border-radius: 5px;
                                border-radius: 5px; 
                            }
                        </style>



                    </div>
                </div>
                
            </div>
        </section>
    </main>
{% endblock %}